apiVersion: v1
kind: Service
metadata:
  name: lychee-service
  labels:
    app: lychee
  annotations:
    external-dns.alpha.kubernetes.io/hostname: something_here
spec:
  ports:
    - port: 80
  selector:
    app: lychee
  type: LoadBalancer
